=== DiosaEstelaa/Examen_3trimestre_LM/examen3trimestreLM/xlm_xsl/reglas.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="tiempo" type="xs:string"/>

        <xs:element name="comunidadAutonoma" type="xs:string"/>


        <xs:element name="provincia" type="xs:string"/>


        <xs:element name="poblacion">

        <xs:complexType> <!-- inicio complexType poblacion  -->
          <xs:sequence>  <!-- inicio secuence poblacion  -->

            <!-- FECHA  -->
            <xs:element name="fecha" type="xs:date"/>

            <!-- TEMP_MAX  -->
            <xs:element name="tempMax" type="xs:decimal"/>

            <!-- TEMP_MIN  -->
            <xs:element name="tempMin" type="xs:decimal"/>

            <!-- PROB_LLUV  -->
            <xs:element name="probLluv" type="xs:decimal"/>

            <!-- AVISO_RIESGO  -->
            <xs:element name="avisoRiesgo" minOccurs="0" maxOccurs="10">
            <xs:simpleType>
                  <xs:restriction base="xs:string">
                  <xs:pattern value="viento|nieve|tormentas|huracan"/>
                  </xs:restriction>
            </xs:simpleType>
            </xs:element>


          </xs:sequence>  <!-- final secuence  -->
        </xs:complexType> <!-- final complexType   -->
    </xs:element>

    
</xs:schema>

<!--
<xs:attribute name="nombreP" type="xs:string" use="optional"/>
        </xs:complexType>

        <xs:attribute name="nombreCM" type="xs:string" use="required"/> 
    
    <xs:attribute name="nombreCM" use="optional">
              <xs:simpleType>
                <xs:restriction base="xs:string"></xs:restriction>
              </xs:simpleType>
          </xs:attribute>-->

=== DiosaEstelaa/Examen_3trimestre_LM/examen3trimestreLM/xlm_xsl/tiempo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- inicio tiempo -->

<tiempo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="reglas.xsd">

<!--<comunidades autonomas>-->
    <comunidadAutonoma >
        <provincia>
            <poblacion>
            
            <prediccion>
              <fecha>2022/05/24</fecha>
              <tempMax>24.0</tempMax>
              <tempMin>9.0</tempMin>
              <probLluv>20.0</probLluv>
              <avisoRiesgo>viento</avisoRiesgo>
            </prediccion>

            <prediccion>
                <fecha>2022/05/23</fecha>
                <tempMax>21.0</tempMax>
                <tempMin>9.0</tempMin>
                <probLluv>45.0</probLluv>
                <avisoRiesgo>viento,lluvia</avisoRiesgo>
              </prediccion>
            </poblacion>
        </provincia>
    </comunidadAutonoma>
    

</tiempo> <!-- fin tiempo -->
